name: generate-artifacts
on:
  push:
    branches:
      - main
      - ci-testing
          
jobs:
  generate:
    runs-on: ubuntu-latest
    container: 
      image: kicad/kicad:nightly-full
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git rev-parse Workaround
        run: git config --global --add safe.directory "*"
      - name: Replace Commit Hash
        run: sed -i -s -e "s/"SH_PLHD"/$(git rev-parse --short ${{ github.sha }})/" pico-logic-analyzer.kicad_pro
      - name: Run Jobset
        run: kicad-cli jobset run --file=generate-artifacts.kicad_jobset pico-logic-analyzer.kicad_pro
      - name: Zip Gerbers
        run: zip -rj generated/gerbers.zip generated/gerbers
      - name: Remove Unzipped Gerbers
        run: rm -rf generated/gerbers
      - name: Push to Branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: main-generated-output
          FOLDER: generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.comf
